driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-7.3
  - name: debian-8.8
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
 - name: server_package
   run_list:
   - recipe[nagios::default]
   - recipe[nrpe::default]
   - recipe[nagios_test::default]
   - role[monitoring]
   attributes:
     nagios:
       monitored_environments:
         - '_default'
 - name: server_source
   run_list:
   - recipe[nagios::default]
   - recipe[nrpe::default]
   - recipe[nagios_test::default]
   - role[monitoring]
   attributes:
     nagios:
       server:
         install_method: 'source'
 - name: pagerduty
   run_list:
   - recipe[nagios::default]
   - recipe[nagios::pagerduty]
   - recipe[nrpe::default]
   - recipe[nagios_test::default]
   - role[monitoring]
   attributes:
     nagios:
       server:
         install_method: 'source'
       pagerduty:
         key: 'your_key_here_3eC2'
 - name: allowed_ips
   run_list:
   - recipe[nagios::default]
   - recipe[nrpe::default]
   - recipe[nagios_test::default]
   - role[monitoring]
   attributes:
     nagios:
       allowed_ips: ['127.0.0.1', '::1']
data_bags_path: test/data_bags
roles_path: test/roles
