driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] || 'latest' %>

data_bags_path: test/fixtures/data_bags
roles_path: test/fixtures/roles

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
    - recipe[apt::default]
  - name: debian-7.11
    run_list:
    - recipe[apt::default]
  - name: debian-8.7
    run_list:
    - recipe[apt::default]
  - name: centos-7.3
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux

suites:
  - name: server_package
    run_list:
    - recipe[nagios::default]
    - recipe[nrpe::default]
    - recipe[nagios_test::default]
    - role[monitoring]
    attributes:
      nagios:
        monitored_environments: [ '_default' ]

  - name: server_source
    run_list:
    - recipe[nagios::default]
    - recipe[nrpe::default]
    - recipe[nagios_test::default]
    - role[monitoring]
    attributes:
      nagios:
        monitored_environments: [ '_default' ]
        server:
          install_method: 'source'

  - name: pagerduty
    run_list:
    - recipe[nagios::default]
    - recipe[nagios::pagerduty]
    - recipe[nrpe::default]
    - recipe[nagios_test::default]
    - role[monitoring]
    attributes:
      nagios:
        monitored_environments: [ '_default' ]
        server:
          install_method: 'source'
        pagerduty:
          key: 'your_key_here_3eC2'
