driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] || 'latest' %>

verifier:
  name: inspec

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.7
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: server_package
    run_list:
    - recipe[nagios::default]
    - recipe[nrpe::default]
    - recipe[nagios_test::default]
    - role[monitoring]
    verifier:
      inspec_tests:
        - test/smoke/server_package
    attributes:
      nagios:
        monitored_environments: [ '_default' ]

  - name: server_source
    run_list:
    - recipe[nagios::default]
    - recipe[nrpe::default]
    - recipe[nagios_test::default]
    - role[monitoring]
    verifier:
      inspec_tests:
        - test/smoke/server_source
    attributes:
      nagios:
        monitored_environments: [ '_default' ]
        server:
          install_method: 'source'

  - name: pagerduty
    run_list:
    - recipe[nagios::default]
    - recipe[nagios::pagerduty]
    - recipe[nrpe::default]
    - recipe[nagios_test::default]
    - role[monitoring]
    verifier:
      inspec_tests:
        - test/smoke/pagerduty
    attributes:
      nagios:
        monitored_environments: [ '_default' ]
        server:
          install_method: 'source'
        pagerduty:
          key: 'your_key_here_3eC2'
