sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=server-package-centos-7 CHEF_VERSION=12.19.36
  - INSTANCE=server-package-centos-7
  - INSTANCE=server-package-debian-8 CHEF_VERSION=12.19.36
  - INSTANCE=server-package-debian-8
  - INSTANCE=server-package-ubuntu-1404
  - INSTANCE=server-package-ubuntu-1604 CHEF_VERSION=12.19.36
  - INSTANCE=server-package-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  allow_failures:
    - env: INSTANCE=server-package-centos-7
    - env: INSTANCE=server-package-debian-8
    - env: INSTANCE=server-package-opensuse-leap
    - env: INSTANCE=server-package-ubuntu-1404
    - env: INSTANCE=server-package-ubuntu-1604
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
